set_property PACKAGE_PIN T18 [get_ports BTN_RST]
    set_property IOSTANDARD LVCMOS33 [get_ports BTN_RST]
    
set_property PACKAGE_PIN T17 [get_ports BTN_DOWN]
    set_property IOSTANDARD LVCMOS33 [get_ports BTN_DOWN]
set_property PACKAGE_PIN W19 [get_ports BTN_UP]
    set_property IOSTANDARD LVCMOS33 [get_ports BTN_UP]

set_property PACKAGE_PIN J18 [get_ports {VGA_B[3]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {VGA_B[3]}]
set_property PACKAGE_PIN K18 [get_ports {VGA_B[2]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {VGA_B[2]}]
set_property PACKAGE_PIN L18 [get_ports {VGA_B[1]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {VGA_B[1]}]
set_property PACKAGE_PIN N18 [get_ports {VGA_B[0]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {VGA_B[0]}]
set_property PACKAGE_PIN D17 [get_ports {VGA_G[3]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {VGA_G[3]}]
set_property PACKAGE_PIN G17 [get_ports {VGA_G[2]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {VGA_G[2]}]
set_property PACKAGE_PIN H17 [get_ports {VGA_G[1]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {VGA_G[1]}]
set_property PACKAGE_PIN J17 [get_ports {VGA_G[0]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {VGA_G[0]}]
set_property PACKAGE_PIN N19 [get_ports {VGA_R[3]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {VGA_R[3]}]
set_property PACKAGE_PIN J19 [get_ports {VGA_R[2]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {VGA_R[2]}]
set_property PACKAGE_PIN H19 [get_ports {VGA_R[1]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {VGA_R[1]}]
set_property PACKAGE_PIN G19 [get_ports {VGA_R[0]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {VGA_R[0]}]

set_property PACKAGE_PIN R19 [get_ports vsync]
    set_property IOSTANDARD LVCMOS33 [get_ports vsync]
set_property PACKAGE_PIN P19 [get_ports hsync]
    set_property IOSTANDARD LVCMOS33 [get_ports hsync]

set_property PACKAGE_PIN W5 [get_ports CLK]
    set_property IOSTANDARD LVCMOS33 [get_ports CLK]

# set_property IOSTANDARD LVCMOS33 [get_ports PS2_CLK]
# set_property IOSTANDARD LVCMOS33 [get_ports PS2_DATA]
# set_property PACKAGE_PIN C17 [get_ports PS2_CLK]
# set_property PACKAGE_PIN B17 [get_ports PS2_DATA]
